version: '3'
services:
  sessionservice:
    container_name: sessionservice
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/vagrant
    links:
      - redis
    tty: true

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
