swagger: '2.0'
info:
  description: This API is for a session service.
  version: "0.2.0"
  title: SessionService API
  # put the contact info for your development or API team
  contact:
    name: Rebel-L
    email: dj@rebel-l.net
    url: https://github.com/rebel-l

  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html

# all paths will be relative to the basePath specified
# basePath: /v1

# tags are used for organizing operations
tags:
- name: external
  description: external calls
- name: internal
  description: secure internal calls
consumes: ['application/json']
produces: ['application/json', 'text/html']
schemes:
- https
- http

securityDefinitions:
  # X-API-Key: abcdef12345
  apiKey:
    type: apiKey
    in: header
    name: X-API-Key
  appId:
    type: apiKey
    in: header
    name: X-APP-ID

paths:
  /docs:
    get:
      tags:
      - external
      operationId: docs
      summary: Endpoint to this documentation.
      description: This is the endpoint to get this documentation.
      produces:
      - text/html
      responses:
        200:
          description: Sends the html for the documentation.
  /ping:
    get:
      tags:
      - external
      operationId: ping
      summary: Quick check if service is operating.
      description: |
        It's a quick check if the service is online and is able to handle requests.
      produces:
      - application/json
      responses:
        200:
          description: session service is operating normal
          schema:
            $ref: '#/definitions/PingResponseSuccess'
        403:
          description: The client is not allowed to do this request.
        503: 
          description: service or storage is unavailable (or both). check the response details.
          schema:
            $ref: '#/definitions/PingResponseFailure'
  /session:
    get:
      security:
      - apiKey: []
      - appId: []
      tags:
      - internal
      summary: Returns a session for a specific id.
      operationId: loadSession
      description: |
        By passing in the appropriate options, you can load the sesions for a 
        specific id. If no id is provided in the parameters it returns a new
        and empty session.
      produces:
      - application/json
      parameters:
      - in: query
        name: id
        description: pass the session id you want to load
        required: false
        type: string
        format: uuid
      - in: query
        name: regenerateId
        description: forces the service to generate a new session id.
        type: boolean
        required: false
      - in: query
        name: keys
        description: a comma seperated list of keys to return in the data object
        required: false
        type: string
        format: field1,field2
      - in: query
        name: domain
        description: an optional domain for the session
        type: string
        format: ^([0-9a-zA-Z-]+[\.])+[0-9a-zA-Z-]+$
        required: false
      responses:
        200:
          description: session id found and returned
          schema:
            $ref: '#/definitions/SessionResponse'
        400:
          description: bad input parameter
        403:
          description: The client is not allowed to do this request.
        404:
          description: session was not found or has expired
    put:
      security:
      - apiKey: []
      - appId: []    
      tags:
      - internal
      summary: updates a session
      operationId: updateSession
      description: Updates the session.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: session
        description: pass the session you want to update
        schema:
          $ref: '#/definitions/SessionBody'
      responses:
        200:
          description: session updated
          schema:
            $ref: '#/definitions/SessionResponse'
        201:
          description: session created if id is omitted in the body
          schema:
            $ref: '#/definitions/SessionResponse'
        400:
          description: invalid input, data invalid
        403:
          description: The client is not allowed to do this request.
        404:
          description: session was not found or has expired
    delete:
      security:
      - apiKey: []
      - appId: []    
      tags:
      - internal
      summary: deletes a session
      operationId: deleteSession
      description: Deletes a session and returns a new empty one.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: id
        description: pass the session id you want to delete
        required: true
        type: string
        format: uuid
      responses:
        200:
          description: session id found and deleted
          schema:
            $ref: '#/definitions/SessionResponse'
        400:
          description: bad input parameter
        403:
          description: The client is not allowed to do this request.
        404:
          description: session was not found or has expired
definitions:
  PingResponseSuccess:
    type: object
    required: 
    - Success
    - Summary
    properties:
      Success:
        type: string
        format: ^OK|FAIL$
        example: OK
      Summary:
        type: object
        required: 
        - Service
        - Storage
        properties:
          Service:
            type: string
            format: ^(PONG)*$
            example: PONG
          Storage:
            type: string
            format: ^(PONG)*$
            example: PONG
  PingResponseFailure:
    type: object
    required: 
    - Success
    - Summary
    properties:
      Success:
        type: string
        format: ^OK|FAIL$
        example: FAIL
      Summary:
        type: object
        required: 
        - Service
        - Storage
        properties:
          Service:
            type: string
            format: ""
            example: ""
          Storage:
            type: string
            format: ^(PONG)*$
            example: ""
  SessionResponse:
    type: object
    required:
    - id
    - data
    - lifetime
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      data:
        type: array
        items:
          $ref: '#/definitions/Data'
      lifetime:
        type: integer
        format: int32
        example: 1800
      expires:
        type: integer
        format: timestamp
        example: 1484485453
      domain:
        type: string
        format: ^([0-9a-zA-Z-]+[\.])+[0-9a-zA-Z-]+$
        example: www.dancedancerevolution.party
  SessionBody:
    type: object
    required:
    - id
    - data
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      data:
        type: array
        items:
          $ref: '#/definitions/Data'
  Data:
    type: object
    required:
    - key
    - value
    properties:
      key:
        type: string
        example: username
      value:
        type: string
        example: Lars
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# Added by API Auto Mocking Plugin
basePath: /rebel-l/Session/1.0.0